name: workbuddy
description: "save time and money"
publish_to: 'none'
version: 0.1.1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

cupertino_icons: ^1.0.6
audiofileplayer: ^2.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  flutter_launcher_icons: ^0.14.1

  flutter_native_splash: ^2.4.1
  #image: "assets/workbuddy_logo_neon_green_512x512.png"

flutter:
  uses-material-design: true
  assets:
   - assets/
   #- assets/"sound05xylophon.wav"