name: workbuddy
description: "save time and money"
publish_to: 'none'
version: 0.1.1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  audioplayers: ^6.1.0
  flutter_exit_app: ^1.1.4
  dropdown_search: ^6.0.1
  searchfield: ^1.1.7

cupertino_icons: ^1.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  flutter_launcher_icons: ^0.14.1
  flutter_native_splash: ^2.4.1
  url_launcher: ^6.3.1

flutter:
  uses-material-design: true
  assets:
   - assets/
   - assets/iconbuttons/
   - assets/company_logos/
   - assets/sound/